name: app_9news
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Disarankan menggunakan rentang versi yang lebih luas

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.5
  http: ^1.2.1 # Versi http yang lebih baru seringkali lebih baik
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Versi lints yang lebih baru

flutter:
  uses-material-design: true

  # Bagian aset yang sudah diperbaiki
  # "assets:" memiliki 2 spasi
  # "-" memiliki 4 spasi
  assets:
    - assets/images/
