name: app_9news
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.5
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # 1. Bagian dependensi (tetap di sini)
  flutter_launcher_icons: "^0.13.1"

# 2. Bagian konfigurasi ikon (diletakkan di sini, di luar dev_dependencies)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
